version: 2
jobs:
  jest:
    docker:
      - image: circleci/node:latest

    steps:
      - add_ssh_keys:
          fingerprints:
            - "69:f9:f4:03:d6:12:18:f3:97:eb:e1:75:7a:1e:65:1a"

      # Use the NPM registry
      - run:
          name: Add NPM_TOKEN
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

      - checkout

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - harvestprofitapicore-yarn-{{ checksum "yarn.lock" }}
            - harvestprofitapicore-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: harvestprofitapicore-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # run jest tests
      - run:
          name: Jest Suite
          command: yarn test --ci
          environment:
            JEST_JUNIT_OUTPUT: "test_results/js-test-results.xml"

      # Save test results for timing analysis
      - store_test_results:
          path: test_results

      - run:
          name: Upload Coverage
          command: ./node_modules/.bin/codecov

      # Automatically deploy docs to gh-pages
      - deploy:
          name: Deploy
          command: yarn run authenticate && yarn run publish-docs

workflows:
  version: 2
  jest:
    jobs:
      - jest
